### ISSUE TITLE
Hemnet Graphql schema?

### ISSUE THREAD

**Issue by sergeiknysh** [ewels/hemnet-commuter#12]
Hi, 
the Hemnet Commuter is a really great MVP! Thanks for that!
Let me ask where can I find more about graphql of Hemnet's API.

**Comment by ewels** [comment]
Good question! I couldn't find documentation or anything, everything here is reverse engineered from intercepting web traffic from the iOS app.

**Comment by sergeiknysh** [comment]
OMG! Great job.
I am not familiar with iOS development. 

As I understand there is a REST API available for brokers only https://integration.hemnet.se/documentation/v1
To develop further a licensed broker is needed in a team.

**Comment by ewels** [comment]
Yes I found that too, but it didn't seem open (or all that helpful). I also don't know much about iOS, I used Proxy Man (https://proxyman.io/) to intercept the requests between my phone and the Hemnet servers. By clearing the log then doing something on your phone you can then see the relevant requests and responses. With a lot of trial and error (mostly using the RESTed mac app - http://www.helloresolven.com/portfolio/rested/ ) I then managed to replicate these requests and edit them a little. It's kind of a fun detective game! 🕵🏻‍♂️ 

Phil

**Comment by sergeiknysh** [comment]
> Yes I found that too, but it didn't seem open (or all that helpful). I also don't know much about iOS, I used Proxy Man (https://proxyman.io/) to intercept the requests between my phone and the Hemnet servers. By clearing the log then doing something on your phone you can then see the relevant requests and responses. With a lot of trial and error (mostly using the RESTed mac app - http://www.helloresolven.com/portfolio/rested/ ) I then managed to replicate these requests and edit them a little. It's kind of a fun detective game! 🕵🏻‍♂️
> 
> Phil

Check your linkedin please
